name: place_tracker
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"
  
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_maps_flutter: ^2.2.0
  provider: ^6.0.2
  uuid: ^4.0.0
  go_router: ">=10.0.0 <15.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

  uses-material-design: true
